user-auth:
  port: 3333
  discovery:
    port: 1111
  docker:
    datasource: jdbc:mysql://localhost:3306/userdb?useSSL=false
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://docker-mysql:3306/userdb?useSSL=false
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: user-auth
    
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
    preferIpAddress: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
